import copy

import numpy as np

from jannik.methods.PV_interface import get_PV_generated
from jannik.methods.helpers import soc2remainingCharge


def compute_additional_columns(car_data):
    """
    adds the column:
    1) electricity generated by PV in MWH
    2) electricity needed by car in MWH
    3) ratio of electricity covered

    Parameters
    ----------
    car_data: pandas df
        data frame containing data about car movements

    Returns
    -------
    car_data_with_extra_column: pandas df
        car data with columns added
    """

    car_data_copy = copy.deepcopy(car_data)
    car_data_copy["generacted_by_PV"] = [get_PV_generated(car_data_copy["start"][car_data_copy.index[i]],
                                                          car_data_copy["end"][car_data_copy.index[i]],
                                                          car_data_copy["vin"][car_data_copy.index[i]]
                                                          ) for i in range(len(car_data_copy.index))]
    print(car_data_copy['soc_start'])
    print(car_data_copy['soc_end'])
    car_data_copy['needed_by_car'] = [soc2remainingCharge(car_data_copy["soc_start"][car_data_copy.index[i]] -
                                      soc2remainingCharge(car_data_copy["soc_end"][car_data_copy.index[i]])
                                                         ) for i in range(len(car_data_copy.index))]
    car_data_copy['coverage_ratio'] = [car_data_copy['generacted_by_PV'][car_data_copy.index[i]] /
                                       car_data_copy['needed_by_car'][car_data_copy.index[i]]
                                       for i in range(len(car_data_copy.index))]
    car_data_copy['charged_from_PV'] = [np.minimum(car_data_copy['generacted_by_PV'][car_data_copy.index[i]] ,
                                                  car_data_copy['needed_by_car'][car_data_copy.index[i]] )
                                       for i in range(len(car_data_copy.index))]

    return car_data_copy
