import datetime

import pint
ureg = pint.UnitRegistry()

import numpy as np

def get_PV_generated(start, end, house_ID):
    """
    interface to house model, fetches generated PV energy by the house from start to end.

    Parameters
    ----------
    start: timestamp
        starting time of query
    end: timestamp
        end time of query
    house_ID: string
        which house is to be queried

    Returns
    -------
    generated_energy: float
        energy that was generated by the house
    """

    """
    #start = datetime.datetime.strptime(start, '%Y-%m-%d %H:%M:%S.%f')
    start = datetime.datetime.strptime(start, '%m/%d/Y H:M')
    end = datetime.datetime.strptime(end, '%m/%d/Y H:M')
    start_hour = start.dt.hour
    end_hour = end.dt.hour
    """

    return 5
